linters:
  enable-all: true
  disable:
    - scopelint
    - interfacer
    - golint
    - maligned
    - varnamelen
    - exhaustivestruct
    - gochecknoglobals
    - paralleltest
    - testpackage
    - wsl
    - nosnakecase
    - deadcode
    - structcheck
    - ifshort
    - varcheck
    - gci
    - exhaustruct
    - gomnd

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      - github.com/facily-tech/go-core/*
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  fix: false
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 1m
  tests: false

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration