
name: Golangci-lint
on:
  ["pull_request"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3


      - name: Run GolangCi Lint
        run: |-
          make lint          
