
name: golangci-lint
on:
  ["pull_request"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Golang lint CI
        run: |-
          mkdir -p $GITHUB_WORKSPACE/bin
          echo "::add-path::$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin"

          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0

          mv ./bin/* $RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)/bin/
          rm -fR ./bin
      - name: Run GolangCi Lint
        run: |-
          make lint          
