
name: Golangci-lint
on:
  ["pull_request"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x'      
      - name: Install Golang lint CI
        run: |-
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.51.2
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Run GolangCi Lint
        run: |-
          make lint          
