
name: golangci-lint
on:
  ["pull_request"]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Golang lint CI
        run: |-
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.43.0
          echo "${GITHUB_WORKSPACE}/bin" >> $GITHUB_PATH

      - name: Run GolangCi Lint
        run: |-
          make lint          
